# Generated by Django 5.0.1 on 2024-04-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceToVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=1000)),
                ('video_path', models.CharField(max_length=2000)),
            ],
        ),
    ]
