# Generated by Django 5.0.1 on 2024-04-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sentencetovideo_video_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencetovideo',
            name='video',
            field=models.BinaryField(),
        ),
    ]
