# Generated by Django 5.0.1 on 2024-04-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sentencetovideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencetovideo',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
