# Generated by Django 5.1.2 on 2025-02-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sentencetovideo_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandImage',
        ),
        migrations.DeleteModel(
            name='SentenceToVideo',
        ),
    ]
